on:
  push:
    branches:
      - main
jobs:
  test:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: setup environment
        run: sudo apt -y install qemu-system-arm ruby-3.0 && gem install ceedling
    
